# Generated by Django 3.1.4 on 2021-04-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_businessregister_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('johar town', 'johar town'), ('pia Society', 'pia Society'), ('dha', 'dha'), ('bahria town', 'bahria town')], max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='SalomImages/')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='SalonImages/')),
                ('center_image', models.ImageField(blank=True, null=True, upload_to='SalonImages/')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessRegister',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='center_image',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='details',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='header',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='location',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='title',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='title_image',
        ),
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='no_of_workers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='serivice_type',
            field=models.CharField(choices=[('home service', 'Home Service'), ('shop', 'Shop'), ('both', 'Both')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='shop_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=100, null=True),
        ),
    ]
