# Generated by Django 3.1.4 on 2021-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_order_salonworker_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='SalonImages/'),
        ),
    ]
