# Generated by Django 3.1.4 on 2021-05-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0011_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
