# Generated by Django 3.1.4 on 2021-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
