# Generated by Django 3.1.4 on 2021-06-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_auto_20210524_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
