# Generated by Django 3.1.4 on 2021-06-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0016_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('close', 'close')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
