# Generated by Django 3.1.4 on 2021-06-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0017_auto_20210617_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='worker',
        ),
        migrations.AddField(
            model_name='slot',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salons.salon'),
        ),
    ]
