# Generated by Django 3.1.4 on 2021-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0019_auto_20210620_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
