# Generated by Django 3.1.4 on 2021-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0022_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('inprogress', 'inprogress'), ('pending', 'pending'), ('complete', 'complete'), ('cartpending', 'cartpending')], max_length=200, null=True),
        ),
    ]
