# Generated by Django 3.1.4 on 2021-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0023_auto_20210626_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('inprogress', 'inprogress'), ('pending', 'pending'), ('complete', 'complete'), ('reject', 'reject')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
