# Generated by Django 3.1.4 on 2021-07-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0024_auto_20210702_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
